### ISSUE TITLE
Double defaultTimestamp config variable in install/etc/cont-init.d/30-leantime

### ISSUE THREAD

**Issue by xpertmind** [tiredofit/docker-leantime#12]
### Summary
There is a double config variable _defaultTimestamp_ in _install/etc/cont-init.d/30-leantime_ file.
This causes the app not working after image update or when container is restarted with following error message:
**Fatal error: Cannot redeclare leantime\core\config::$defaultTimezone in /www/html/config/configuration.php on line 14**

### Steps to reproduce
define TIMEZONE as environment variable
i.e. using docker compose       - TIMEZONE=Europe/Zagreb

Stop container, remove it, restart. 

### Possible fixes
Just remove either line **130** or line **133** in _install/etc/cont-init.d/30-leantime_ file.

**Comment by tiredofit** [comment]
Thanks! Solved in `1.0.27`
